version: '3'

services:
  
  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    # volumes:
    #   - ./src:/var/www/html
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    # depends_on:
    #   - php